# Cosmos Common Configuration

# Enable Bluetooth
CONFIG_ZMK_BLE=y
CONFIG_ZMK_USB=y

# Split keyboard
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=1
CONFIG_ZMK_SPLIT_BLE_ROLE_CENTRAL_PREFERRED=y

# Bluetooth settings
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Extra features
CONFIG_ZMK_EXTERNAL_POWER=y

# Performance
CONFIG_ZMK_USB_LOGGING=n
