#!/usr/bin/env python3

import argparse
import json
import sys
from pathlib import Path

from PIL import Image


DISPLAY_WIDTH = 400
DISPLAY_HEIGHT = 240


def pack_1bit(image):
    """
    Pack a 1-bit image MSB-first, one row at a time.

    LVGL indexed 1-bit images use one bit per pixel.
    """
    width, height = image.size
    row_bytes = (width + 7) // 8

    data = bytearray()

    for y in range(height):
        for byte_x in range(row_bytes):
            value = 0

            for bit in range(8):
                x = byte_x * 8 + bit

                if x >= width:
                    break

                # PIL mode "1":
                # 0 = black
                # 255 = white
                pixel = image.getpixel((x, y))

                # LVGL palette:
                # index 0 = white
                # index 1 = black
                #
                # Therefore black pixels get bit value 1.
                if pixel == 0:
                    value |= 1 << (7 - bit)

            data.append(value)

    return bytes(data)


def make_lvgl_data(image):
    """
    Build LVGL LV_IMG_CF_INDEXED_1BIT image data.

    Layout:

        8-byte palette
        packed 1-bit pixel data

    Palette entries are 4 bytes each:

        Blue
        Green
        Red
        Alpha
    """

    # LVGL indexed palette:
    #
    # index 0 = white
    # index 1 = black
    #
    # BGRA byte ordering used by LVGL's palette representation.
    palette = bytes([
        0xFF, 0xFF, 0xFF, 0xFF,  # white
        0x00, 0x00, 0x00, 0xFF,  # black
    ])

    pixels = pack_1bit(image)

    return palette + pixels


def load_metadata(path):
    with path.open("r", encoding="utf-8") as f:
        metadata = json.load(f)

    frames = metadata.get("frames")

    if not isinstance(frames, dict) or not frames:
        raise ValueError("JSON contains no frames")

    return metadata, frames


def fit_dimensions(source_width, source_height):
    scale = min(
        DISPLAY_WIDTH / source_width,
        DISPLAY_HEIGHT / source_height,
    )

    width = max(1, round(source_width * scale))
    height = max(1, round(source_height * scale))

    return width, height


def write_c_file(output_path, sprites, width, height):
    output_path.parent.mkdir(parents=True, exist_ok=True)

    row_bytes = (width + 7) // 8
    pixel_bytes = row_bytes * height
    data_bytes = pixel_bytes + 8

    with output_path.open("w", encoding="utf-8") as f:

        f.write("/*\n")
        f.write(" * Auto-generated by png_to_sprite_c.py\n")
        f.write(" * DO NOT EDIT MANUALLY.\n")
        f.write(" */\n\n")

        f.write("#include <stdint.h>\n")
        f.write("#include <lvgl.h>\n")
        f.write("#include \"../display/six_by_six_display.h\"\n\n")

        f.write(
            f"#define SIX_BY_SIX_SPRITE_COUNT {len(sprites)}\n"
        )
        f.write(
            f"#define SIX_BY_SIX_SPRITE_WIDTH {width}\n"
        )
        f.write(
            f"#define SIX_BY_SIX_SPRITE_HEIGHT {height}\n"
        )
        f.write(
            f"#define SIX_BY_SIX_SPRITE_ROW_BYTES {row_bytes}\n"
        )
        f.write(
            f"#define SIX_BY_SIX_SPRITE_DATA_BYTES {data_bytes}\n\n"
        )

        # ---------------------------------------------------------
        # Bitmap data
        # ---------------------------------------------------------

        for sprite in sprites:
            number = sprite["number"]
            data = sprite["data"]

            f.write(
                f"static const uint8_t "
                f"six_by_six_sprite_{number}_data"
                f"[{len(data)}] = {{\n"
            )

            for offset in range(0, len(data), 16):
                chunk = data[offset:offset + 16]

                f.write("    ")
                f.write(
                    ", ".join(
                        f"0x{value:02X}"
                        for value in chunk
                    )
                )
                f.write(",\n")

            f.write("};\n\n")

        # ---------------------------------------------------------
        # LVGL image descriptors
        # ---------------------------------------------------------

        for sprite in sprites:
            number = sprite["number"]

            f.write(
                f"const lv_img_dsc_t "
                f"six_by_six_sprite_{number}_image = {{\n"
            )

            f.write("    .header = {\n")
            f.write("        .always_zero = 0,\n")
            f.write(f"        .w = {width},\n")
            f.write(f"        .h = {height},\n")
            f.write("        .cf = LV_IMG_CF_INDEXED_1BIT,\n")
            f.write("    },\n")

            f.write(
                f"    .data_size = {len(sprite['data'])},\n"
            )

            f.write(
                f"    .data = six_by_six_sprite_{number}_data,\n"
            )

            f.write("};\n\n")

        # ---------------------------------------------------------
        # Sprite metadata table
        # ---------------------------------------------------------

        f.write(
            "const struct six_by_six_sprite "
            "six_by_six_sprites[] = {\n"
        )

        for sprite in sprites:
            number = sprite["number"]

            f.write("    {\n")

            f.write(
                f"        .data = "
                f"six_by_six_sprite_{number}_data,\n"
            )

            f.write(f"        .width = {width},\n")
            f.write(f"        .height = {height},\n")
            f.write(
                f"        .duration_ms = "
                f"{sprite['duration']},\n"
            )

            f.write("    },\n")

        f.write("};\n\n")

        # ---------------------------------------------------------
        # Image descriptor table
        # ---------------------------------------------------------

        f.write(
            "const lv_img_dsc_t *"
            "six_by_six_sprite_images[] = {\n"
        )

        for sprite in sprites:
            number = sprite["number"]

            f.write(
                f"    &six_by_six_sprite_{number}_image,\n"
            )

        f.write("};\n\n")

        # ---------------------------------------------------------
        # Public metadata
        # ---------------------------------------------------------

        f.write(
            "const uint16_t six_by_six_sprite_count = "
            f"{len(sprites)};\n"
        )

        f.write(
            "const uint16_t six_by_six_sprite_width = "
            f"{width};\n"
        )

        f.write(
            "const uint16_t six_by_six_sprite_height = "
            f"{height};\n"
        )


def main():
    parser = argparse.ArgumentParser(
        description=(
            "Convert a PNG sprite sheet and JSON frame metadata "
            "into LVGL 1-bit image descriptors."
        )
    )

    parser.add_argument(
        "input_png",
        type=Path,
        help="Input PNG sprite sheet",
    )

    parser.add_argument(
        "input_json",
        type=Path,
        help="JSON sprite metadata",
    )

    parser.add_argument(
        "output_c",
        type=Path,
        help="Output C source file",
    )

    parser.add_argument(
        "--width",
        type=int,
        default=400,
        help="Display width (default: 400)",
    )

    parser.add_argument(
        "--height",
        type=int,
        default=240,
        help="Display height (default: 240)",
    )

    args = parser.parse_args()

    if not args.input_png.exists():
        print(
            f"ERROR: PNG not found: {args.input_png}",
            file=sys.stderr,
        )
        return 1

    if not args.input_json.exists():
        print(
            f"ERROR: JSON not found: {args.input_json}",
            file=sys.stderr,
        )
        return 1

    try:
        metadata, frames = load_metadata(args.input_json)

        image = Image.open(args.input_png)

        print(
            f"Input image: "
            f"{image.width}x{image.height}"
        )

        print(f"Frames: {len(frames)}")

        frame_size = metadata["meta"]["frameSize"]

        source_width = int(frame_size["w"])
        source_height = int(frame_size["h"])

        # Calculate output dimensions using the requested display size.
        scale = min(
            args.width / source_width,
            args.height / source_height,
        )

        output_width = max(
            1,
            round(source_width * scale),
        )

        output_height = max(
            1,
            round(source_height * scale),
        )

        print(
            f"Scaling "
            f"{source_width}x{source_height} -> "
            f"{output_width}x{output_height}"
        )

        row_bytes = (output_width + 7) // 8
        pixel_bytes = row_bytes * output_height
        total_bytes = pixel_bytes + 8

        print(f"Row bytes: {row_bytes}")
        print(f"Pixel bytes/frame: {pixel_bytes}")
        print(f"LVGL data bytes/frame: {total_bytes}")

        sprites = []

        frame_items = sorted(
            frames.items(),
            key=lambda item: int(item[0]),
        )

        for frame_number, frame in frame_items:
            number = int(frame_number)

            x = int(frame["x"])
            y = int(frame["y"])
            w = int(frame["w"])
            h = int(frame["h"])

            duration = int(
                frame.get("duration", 50)
            )

            print(
                f"Frame {number}: "
                f"({x},{y}) "
                f"{w}x{h}, "
                f"{duration}ms"
            )

            cropped = image.crop(
                (
                    x,
                    y,
                    x + w,
                    y + h,
                )
            )

            # Composite transparent pixels onto white.
            if "A" in cropped.getbands():
                rgba = cropped.convert("RGBA")

                background = Image.new(
                    "RGBA",
                    rgba.size,
                    (255, 255, 255, 255),
                )

                cropped = Image.alpha_composite(
                    background,
                    rgba,
                ).convert("L")
            else:
                cropped = cropped.convert("L")

            resized = cropped.resize(
                (
                    output_width,
                    output_height,
                ),
                Image.Resampling.LANCZOS,
            )

            monochrome = resized.convert(
                "1",
                dither=Image.Dither.NONE,
            )

            data = make_lvgl_data(
                monochrome
            )

            sprites.append(
                {
                    "number": number,
                    "width": output_width,
                    "height": output_height,
                    "duration": duration,
                    "data": data,
                }
            )

        write_c_file(
            args.output_c,
            sprites,
            output_width,
            output_height,
        )

        bitmap_total = sum(
            len(sprite["data"])
            for sprite in sprites
        )

        source_size = args.output_c.stat().st_size

        print()
        print("========================================")
        print("Conversion complete")
        print("========================================")
        print(f"Output:             {args.output_c}")
        print(f"Frames:             {len(sprites)}")
        print(
            f"Dimensions:         "
            f"{output_width}x{output_height}"
        )
        print(f"Row bytes:          {row_bytes}")
        print(f"Bytes/frame:        {total_bytes}")
        print(
            f"Total bitmap data:  "
            f"{bitmap_total:,} bytes"
        )
        print(
            f"C source size:      "
            f"{source_size:,} bytes"
        )
        print("========================================")

        return 0

    except Exception as exc:
        print(
            f"ERROR: {exc}",
            file=sys.stderr,
        )
        return 1
if __name__ == "__main__":
    sys.exit(main())